version: '3.8'

networks:
  default:

volumes:
  postgres-data:

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: development.Dockerfile
    volumes:
      - ../src:/var/www/html:delegated
    depends_on:
      - postgres
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE-off}"
      XDEBUG_CONFIG: 'start_with_request=yes client_host=${XDEBUG_CONFIG_CLIENT_HOST-} idekey=${XDEBUG_CONFIG_IDEKEY-}'

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: root
