CREATE USER gecon WITH PASSWORD 'secret';
CREATE DATABASE gecon WITH OWNER gecon ENCODING 'utf8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE gecon TO gecon;
